- name: Deploy nginx sites configuration
  template: src=mysite.j2 dest="/etc/nginx/sites-enabled/mysite"
  notify: restart nginx
  tags: configuration

- name: Remove defaults
  file: path="/etc/nginx/sites-enabled/default" state=absent
  tags: configuration