- name: ensure apache is the latest version
  apt:
    name: apache2
    state: latest
  tags: installation

- name: write the apache2 ports.conf config file
  template:
    src: templates/ports.conf.j2
    dest: /etc/apache2/ports.conf
  notify:
  - restart apache
  tags: configuration

- name: write the index file
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
  notify:
  - restart apache
  tags: configuration

- name: ensure apache is running
  service:
    name: apache2
    state: started